// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC82m9RpGHiuRUYyx6zkpTG7svHGgPdfkE',
    appId: '1:25705781231:web:082222ab14db017b1bc81a',
    messagingSenderId: '25705781231',
    projectId: 'archeun-minco',
    authDomain: 'archeun-minco.firebaseapp.com',
    storageBucket: 'archeun-minco.appspot.com',
    measurementId: 'G-0ND7BJP9BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgd_Qx-Qo1YReRcDuySrYOPmrSobRy7Xc',
    appId: '1:25705781231:android:353e3540ff71e6b11bc81a',
    messagingSenderId: '25705781231',
    projectId: 'archeun-minco',
    storageBucket: 'archeun-minco.appspot.com',
  );
}
